### ISSUE TITLE
python3

### ISSUE THREAD

**Issue by EmadDeve20** [antonioCoco/SharPyShell#10]
This project is finished?
can help You if You need this project and support for python3?

**Comment by antonioCoco** [comment]
Hi EmaDeve20,

this project is still alive and i'm just finding some time to revamp the whole project. The first thing to do is for sure the porting to python3. 

If you would like to contribute in the port to python3 feel free to send a PR. I have created a new branch for it --> https://github.com/antonioCoco/SharPyShell/tree/py3 

Thanks!

**Comment by EmadDeve20** [comment]
ok, brother :D
my os is Linux first I test your project in my os if not no problem, I read your source, and finally I sending PL.
but I have some work and I need time but I work for it if is not a problem in my os :D

**Comment by antonioCoco** [comment]
solved in #18
