### ISSUE TITLE
Error No module named prettytable

### ISSUE THREAD

**Issue by theleecher** [antonioCoco/SharPyShell#12]
When i run python SharpyShell.py i got this error 
![sharpyshell](https://user-images.githubusercontent.com/16206326/107332407-cebfbc00-6abc-11eb-8bd1-4b9e7973f45a.png)

**Comment by Tensha** [comment]
same issue here.
Its probably because the difference from python to python3.
If you try Python3 SharPyShell the module is ok but you get another error.

**Comment by antonioCoco** [comment]
SharPyShell supports only python2 atm.
The error you are having is that you are using pip to install libs on py3 and you are running SharPyShell with python2 interpreter.

Run `which pip` and ensure that the pip script is running from python2 interpreter. It will allows to install libraries in the python2 dir.

Anyway i will port the whole project to py3 in the next release.
