### ISSUE TITLE
SSLError: [SSL] internal error (_ssl.c:727)

### ISSUE THREAD

**Issue by donjuanme** [antonioCoco/SharPyShell#13]
any idea why this will happen

{{{Offline}}}{{{GetTempDirectoryException}}}{{{PythonError}}}
Traceback (most recent call last):

  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL] internal error (_ssl.c:727)

**Comment by antonioCoco** [comment]
It's not a bug. It seems the site you are reaching is offline. Please next time include more information, e.g. full commandline of sharpyshell you are using and full output received with the error.

**Comment by NgoHuy** [comment]
I send pull request  https://github.com/antonioCoco/SharPyShell/pull/21 for this. Because the webserver doesnot support TLSv1
