### ISSUE TITLE
403

### ISSUE THREAD

**Issue by fendi1989** [antonioCoco/SharPyShell#15]
can't execute anything , a long response with 403 error when execution any command.

any help please?

**Comment by b4sh1t1** [comment]
From where you running ? 

can you give a screenshot.

**Comment by fendi1989** [comment]
Yes I will add it tommorow now I'm using my phone. I think I didn't upload the shell in the right path on the target. Does the path matters when interacting with the shell? 
Thx

**Comment by fendi1989** [comment]
<img width="782" alt="403" src="https://user-images.githubusercontent.com/44947513/134493985-b9b86f5e-dc9a-4c1c-8605-b9021bb98fb3.png">

**Comment by b4sh1t1** [comment]
It's catched by the antivirus; 

Keep in mind; you can decode/upload the shell to bypass most of AV/EDR but once the connection success it's catched and deleted; 

so you need to make some obfuscated of the shell value to be able to bypass it or wait an update from the author here.

**Comment by fendi1989** [comment]
403 is forbidden then its the antivirus ; mmm ok thx

**Comment by antonioCoco** [comment]
It seems the page is backed by an authentication. Next time try to upload a simple txt file and try to browse it. If it returns a 403 it means it has nothing to do with the webshell implementation.

If the antivirus catch the webshell agent the error code you should see is 404 and not 403.
