### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by n3rada** [antonioCoco/SharPyShell#22]
Hello @antonioCoco,

I would like to know if this project is still maintained or not. I would like to add [GodPotato](https://github.com/BeichenDream/GodPotato) and your fabulous [JuicyPotatoNG](https://github.com/antonioCoco/JuicyPotatoNG), a command [ConPtyShell](https://github.com/antonioCoco/ConPtyShell) to send it to your machine to get a better shell and other features.

Could you let me know if you are able to accept Pull-Requests or if I can help you as a maintainer, etc.?

Best regards,

**Comment by NgoHuy** [comment]
you are free to send pull request.

**Comment by n3rada** [comment]
Of course, but if there's no one to respond to a pull request like yours, that's why I asked!

**Comment by NgoHuy** [comment]
Anyone can merge it locally on their side, if they need feature or bug fix likes you

**Comment by n3rada** [comment]
I clearly understand how it works. The point here is to have a centralised repository. That's the whole point 😅.

**Comment by antonioCoco** [comment]
Hi,

the project is still maintained but there are no actual plans to extend its functionalities. I usually fix or merge only important bugs.

You are free to send the PR you would like, but i cannot guarantee you i will be able to test your code and merge it into the master branch anytime soon.
