### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [antonioCoco/SharPyShell#5]
Hello! I was just reading through your project and I'd like to contribute to it by designing a logo. If you'd want that too, please let me know if there are any specific things you'd want this logo to represent, and if you don't have any I'll just implement my own ideas. Looking forward to hearing from you :)

**Comment by antonioCoco** [comment]
Hi @newfinal100,
yes, sure. It would be great!
You are free to implement your ideas on the logo :)

If it can helps, the concept behind the name is:

Sharp = because all the attacks of this framework are based on C# language
Py = because all of the framework is written in Python language
Shell = because the framework simulate a pseudo-terminal (shell) to interact with in order to launch commands

Let me know if you need additional details.

**Comment by newfinal100** [comment]
So I created these few variations, let me know what you think! If you'd want me to make other variations or change something in these feel free to tell me :)

![first variation sharpyshell-01](https://user-images.githubusercontent.com/49202520/56083982-9e5d5700-5e2c-11e9-87ed-42ac9f659b0c.jpg)
![second variation sharpyshell-01](https://user-images.githubusercontent.com/49202520/56083983-a4533800-5e2c-11e9-9993-1b8bed529eb2.jpg)

**Comment by antonioCoco** [comment]
I really like the first one. :)
I would like to see some variation of that on the font. Some terminal font like this:

https://www.fontsquirrel.com/fonts/ubuntu-mono

A variation with S P S only capital letters would be appreciated.

Thanks!

**Comment by newfinal100** [comment]
Sure! Here are some variations:

![font variations SharPyShell-01](https://user-images.githubusercontent.com/49202520/56085340-a07de080-5e41-11e9-8b1a-9a20dbf23392.jpg)

For the first one I used the font you mentioned :)

**Comment by antonioCoco** [comment]
The 6 is awesome and i think it can fit perfectly the whole project!

**Comment by newfinal100** [comment]
I'm glad you liked it! I'll upload that one in all the formats you may need on Google Drive and I'll share the link with you here so you can use the logo :)

**Comment by newfinal100** [comment]
Here's the link:
https://drive.google.com/drive/folders/12_nTaKrkWojViPbuf_VZV2KjZXor2kbD?usp=sharing

Let me know if you need anything else!

**Comment by antonioCoco** [comment]
Great!
I will update the readme with the new fancy logo in the next release. I hope by the end of the month. :)
