### ISSUE TITLE
SharPyShell Cannot run the script

### ISSUE THREAD

**Issue by Agile-colud** [antonioCoco/SharPyShell#9]
Hello, my python version on CENTOS is 2.7.17
Cannot run this script.

Please provide details of your successful operation environment.

I like this tool very much. Please help me to resolve this problem.

**Comment by Agile-colud** [comment]
PYTHON 2.7.17 CENTOS7

  File "/usr/lib64/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)



Target Offline...

**Comment by antonioCoco** [comment]
The error is indicating a failure in the certification validation.

try to use the flag --insecure in the interact command and it should solve the issue.
